[phases.setup]
nixPkgs = ['python310', 'gcc']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'gunicorn flask_app:app --bind 0.0.0.0:'
