[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn flask_app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"